
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed @fixed;

	private global::Gtk.DrawingArea drawingarea;

	private global::Gtk.Button button;

	private global::Gtk.HScale hscale;

	private global::Gtk.Label label;

	private global::Gtk.Button button1;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.@fixed = new global::Gtk.Fixed();
		this.@fixed.Name = "fixed";
		this.@fixed.HasWindow = false;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.drawingarea = new global::Gtk.DrawingArea();
		this.drawingarea.WidthRequest = 500;
		this.drawingarea.HeightRequest = 300;
		this.drawingarea.Name = "drawingarea";
		this.@fixed.Add(this.drawingarea);
		// Container child fixed.Gtk.Fixed+FixedChild
		this.button = new global::Gtk.Button();
		this.button.CanFocus = true;
		this.button.Name = "button";
		this.button.UseUnderline = true;
		this.button.Label = global::Mono.Unix.Catalog.GetString("Randomize data");
		this.@fixed.Add(this.button);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.@fixed[this.button]));
		w2.X = 387;
		w2.Y = 303;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.hscale = new global::Gtk.HScale(null);
		this.hscale.WidthRequest = 228;
		this.hscale.CanFocus = true;
		this.hscale.Name = "hscale";
		this.hscale.Adjustment.Lower = 10D;
		this.hscale.Adjustment.Upper = 250D;
		this.hscale.Adjustment.PageIncrement = 1D;
		this.hscale.Adjustment.StepIncrement = 1D;
		this.hscale.Adjustment.Value = 10D;
		this.hscale.DrawValue = true;
		this.hscale.Digits = 0;
		this.hscale.ValuePos = ((global::Gtk.PositionType)(2));
		this.@fixed.Add(this.hscale);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.@fixed[this.hscale]));
		w3.X = 75;
		w3.Y = 300;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.label = new global::Gtk.Label();
		this.label.Name = "label";
		this.label.LabelProp = global::Mono.Unix.Catalog.GetString("Sample size");
		this.@fixed.Add(this.label);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.@fixed[this.label]));
		w4.X = 3;
		w4.Y = 318;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Sort");
		this.@fixed.Add(this.button1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.@fixed[this.button1]));
		w5.X = 345;
		w5.Y = 303;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Buble"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Insertion"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Quick"));
		this.combobox1.WidthRequest = 200;
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.@fixed.Add(this.combobox1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.@fixed[this.combobox1]));
		w6.Y = 344;
		// Container child fixed.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("sort");
		this.@fixed.Add(this.label1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.@fixed[this.label1]));
		w7.X = 205;
		w7.Y = 352;
		this.Add(this.@fixed);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 500;
		this.DefaultHeight = 383;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawingareaExposeEvent);
		this.button.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.hscale.ValueChanged += new global::System.EventHandler(this.OnHscaleValueChanged);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
	}
}
